version: "3.9"

services:
  postgres:
    image: postgres:13.3
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./assets/postgres/init.sql:/docker-entrypoint-initdb.d/1-schema.sql

volumes:
  pgdata:
